name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 5
        submodules: true

    # - name: submodules recursively
    #   run: git submodule update --init --recursive

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake clang gcc ninja-build git

    - name: Configure
      run: |
        mkdir -p build

    - name: build
      run: |
        cd build
        cmake .. -DSANITIZE_ADDRESS=On
        make -j16
